👍 fix typo

diff --git a/src/bin/github_issue_selector_preview b/src/bin/github_issue_selector_preview
--- a/src/bin/github_issue_selector_preview
+++ b/src/bin/github_issue_selector_preview
@@ -22,7 +22,7 @@ else
     local issue_num="$REPLY"
     local pipe_mode='true'
   else
-    echo "error: empty imput." 1>&2
+    echo "error: empty input." 1>&2
     return 1
   fi
 fi
